### ISSUE TITLE
Error: receiver not registered

### ISSUE THREAD

**Issue by etam** [yolosec/routerkeygenAndroid#5]
I just installed this app from f-droid and it doesn't work. It says "no wifi networks detected". This is what appears in the logs:
```
Unregister error
java.lang.IllegalArgumentException: Receiver not registered: org.exobel.routerkeygen.WifiScanReceiver@767c866
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1007)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1330)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:608)
	at org.exobel.routerkeygen.ui.NetworksListActivity.onStop(NetworksListActivity.java:270)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1290)
	at android.app.Activity.performStop(Activity.java:6859)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3900)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3952)
	at android.app.ActivityThread.-wrap25(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
 
I'm running on LineageOS 14.1

**Comment by etam** [comment]
It looks like https://github.com/routerkeygen/routerkeygenAndroid/issues/37 , which is supposed to be fixed

**Comment by bboyDmT** [comment]
Hi, i have lg g3 and android 6.0. App does not find any networks. However works fine (finds networks) on my older phones with android 4. Installed from fdroid.

**Comment by ph4r05** [comment]
> Hi, i have lg g3 and android 6.0. App does not find any networks. However works fine (finds networks) on my older phones with android 4. Installed from fdroid.

Try enabling location permissions (fine and coarse)

**Comment by bboyDmT** [comment]
Location enabled, no fine and coarse settings available. Just location permission and storage permission, both enabled.
