### ISSUE TITLE
App crashes when clicking on Sitecom router

### ISSUE THREAD

**Issue by TomJansen** [yolosec/routerkeygenAndroid#8]
The app crashes every time I click a sitecom router
Here is the logcat

> 07-27 21:31:14.604  2819  2819 E AndroidRuntime: Process: net.yolosec.routerkeygen2, PID: 2819
07-27 21:31:14.604  2819  2819 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.yolosec.routerkeygen2/org.exobel.routerkeygen.ui.NetworkActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@cbe3cee: Unmarshalling unknown type code 6619252 at offset 424
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-27 21:31:14.604  2819  2819 E AndroidRuntime: Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@cbe3cee: Unmarshalling unknown type code 6619252 at offset 424
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2444)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readListInternal(Parcel.java:2793)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readList(Parcel.java:1836)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at org.exobel.routerkeygen.algorithms.WiFiNetwork.<init>(WiFiNetwork.java:80)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at org.exobel.routerkeygen.algorithms.WiFiNetwork.<init>(WiFiNetwork.java:17)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at org.exobel.routerkeygen.algorithms.WiFiNetwork$1.createFromParcel(WiFiNetwork.java:32)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at org.exobel.routerkeygen.algorithms.WiFiNetwork$1.createFromParcel(WiFiNetwork.java:24)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readParcelable(Parcel.java:2471)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2365)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Parcel.readArrayMapInternal(Parcel.java:2732)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.BaseBundle.unparcel(BaseBundle.java:271)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.os.Bundle.getParcelable(Bundle.java:864)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.content.Intent.getParcelableExtra(Intent.java:6287)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at org.exobel.routerkeygen.ui.NetworkActivity.onCreate(NetworkActivity.java:44)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6684)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
07-27 21:31:14.604  2819  2819 E AndroidRuntime:        ... 9 more
07-27 21:31:14.608   608 14950 W ActivityManager:   Force finishing activity net.yolosec.routerkeygen2/org.exobel.routerkeygen.ui.NetworkActivity
07-27 21:31:14.615   608 14950 W ActivityManager:   Force finishing activity net.yolosec.routerkeygen2/org.exobel.routerkeygen.ui.NetworksListActivity

**Comment by TomJansen** [comment]
Yes. It happens every time, with every sitecom router.

**Comment by TomJansen** [comment]
I think that this commit would fix this issue, but I don't know for sure
https://github.com/routerkeygen/routerkeygenAndroid/pull/30/files
